// Generated by npm run build. Edit src/client.cjs.
window.__ModuleLoader__.load({id:"dsh-inapp-browser",factory:(require)=>{
const module={exports:{}};const exports=module.exports;
/* Wrapped by scripts/build.mjs in the Harness module-loader factory. React is provided by the host. */
const React = require('react');
const {createElement: h, useEffect, useRef, useState} = React;
const TAB = 'dsh-inapp-browser:view';
const API = '/dsh-inapp-browser/api/';

function createApi() {
  let tokenPromise;
  async function token() {
    if (!tokenPromise) tokenPromise = fetch(API + 'bootstrap', {method: 'POST', headers: {'x-dsh-iab': '1'}})
      .then(async r => { const j = await r.json(); if (!r.ok) throw new Error(j.error); return j.token; })
      .catch(e => { tokenPromise = undefined; throw e; });
    return tokenPromise;
  }
  async function request(method, args, signal) {
    const response = await fetch(API + method, {
      method: 'POST', headers: {'Content-Type': 'application/json', 'x-dsh-iab': '1', 'x-dsh-iab-token': await token()},
      body: JSON.stringify(args), signal,
    });
    if (response.status === 401) tokenPromise = undefined;
    if (!response.ok) { const j = await response.json(); throw new Error(j.error || '浏览器连接失败'); }
    return response;
  }
  return {request, async call(method, args = {}, signal) { return (await request(method, args, signal)).json(); }};
}

function BrowserPanel({scope, visible = true, api}) {
  const desktop = window.dshIabDesktop;
  const sessionId = scope.sessionId;
  const [state, setState] = useState({tabs: [], paused: false, aiRunning: false, width: 1280, height: 800});
  const [image, setImage] = useState(null);
  const [address, setAddress] = useState('');
  const [engine, setEngine] = useState('bing');
  const [more, setMore] = useState(false);
  const [error, setError] = useState('');
  const [status, setStatus] = useState('正在启动本地浏览器…');
  const [nonce, setNonce] = useState(0);
  const [stopped, setStopped] = useState(false);
  const [busy, setBusy] = useState(false);
  const [pauseBusy, setPauseBusy] = useState(false);
  const viewportRef = useRef(null);
  const hoverPending = useRef(false);
  const imgRef = useRef(null), inputRef = useRef(null), stateRef = useRef(state), addressFocus = useRef(false);
  const composing = useRef(false), inputQueue = useRef(Promise.resolve()), down = useRef(false), moveTime = useRef(0);
  stateRef.current = state;
  async function call(method, args = {}) {
    try { return await api.call(method, {...args, sessionId}); }
    catch (e) { setError(e.message); throw e; }
  }
  const merge = next => {
    if (next.error) setError(next.error);
    setState(old => ({...old, ...next}));
    if (next.url && !addressFocus.current) setAddress(next.url === 'about:blank' ? '' : next.url);
  };
  useEffect(() => {
    if (!visible || stopped) return;
    const abort = new AbortController();
    let live = true, pendingFrame = null, decoding = false;
    async function displayFrame(frame) {
      pendingFrame = frame;
      if (decoding) return;
      decoding = true;
      try {
        while (live && pendingFrame) {
          const next = pendingFrame; pendingFrame = null;
          const src = 'data:' + (next.mimeType === 'image/png' ? 'image/png' : 'image/jpeg') + ';base64,' + next.image;
          const decoded = new Image(); decoded.src = src;
          try { await decoded.decode(); } catch { continue; }
          if (live && (!pendingFrame || pendingFrame.revision === next.revision)) setImage({...next, src});
        }
      } finally { decoding = false; }
    }
    setError(''); setStatus('正在连接本地浏览器…');
    (async () => {
      if (desktop) {
        const next = await api.call('state', {sessionId}, abort.signal);
        if (next.mode !== 'native' || next.desktopId !== desktop.id) throw new Error('此会话尚未连接当前原生桌面。请关闭旧浏览器会话后重新启动桌面端。');
        if (!live) return; merge(next); setStatus('原生浏览器');
        while (live) {
          await new Promise(resolve => setTimeout(resolve, 750));
          if (!live) break;
          merge(await api.call('state', {sessionId}, abort.signal));
        }
        return;
      }
      const response = await api.request('stream', {sessionId}, abort.signal);
      if (!live) return;
      setStatus('已连接');
      const reader = response.body.getReader(), decoder = new TextDecoder();
      let pending = '';
      while (live) {
        const {value, done} = await reader.read();
        if (done) throw new Error('浏览器连接已断开，请点击“重新连接”。');
        pending += decoder.decode(value, {stream: true});
        let at;
        while ((at = pending.indexOf('\n')) >= 0) {
          const line = pending.slice(0, at); pending = pending.slice(at + 1);
          if (!line) continue;
          const packet = JSON.parse(line);
          if (packet.kind === 'frame') void displayFrame(packet.value);
          if (packet.kind === 'state') merge(packet.value);
        }
      }
    })().catch(e => { if (live && e.name !== 'AbortError') { setError(e.message); setStatus('未连接'); } });
    return () => { live = false; abort.abort(); };
  }, [sessionId, visible, nonce, stopped]);
  useEffect(() => {
    if (!desktop || stopped || !visible || state.mode !== 'native') return;
    const el = viewportRef.current;
    const update = () => {
      const r = el.getBoundingClientRect();
      const center = document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2);
      const shown = !document.hidden && r.width > 1 && r.height > 1 && (center === el || el.contains(center));
      desktop.layout({sessionId, visible: shown, bounds: {x: r.x, y: r.y, width: r.width, height: r.height}});
    };
    const observer = new ResizeObserver(update); observer.observe(el); update();
    const timer = setInterval(update, 200);
    window.addEventListener('resize', update);
    return () => { clearInterval(timer); observer.disconnect(); window.removeEventListener('resize', update); desktop.layout({sessionId, visible: false}); };
  }, [sessionId, visible, stopped, state.mode]);
  useEffect(() => {
    if (desktop || !visible || stopped || !image) return;
    let timer, previous = '', alive = true;
    const update = () => {
      clearTimeout(timer);
      timer = setTimeout(() => {
        if (!alive) return;
        const r = viewportRef.current.getBoundingClientRect();
        if (r.width < 240 || r.height < 160) return;
        const [width, height] = [Math.max(240, Math.min(2560, Math.round(r.width))), Math.max(160, Math.min(1600, Math.round(r.height)))];
        const pixelRatio = Math.max(1, Math.min(2, window.devicePixelRatio || 1));
        const key = `${width}/${height}/${pixelRatio}`;
        if (key === previous) return; previous = key;
        void manual('resize', {width, height, pixelRatio}).then(next => { if (alive) merge(next); }).catch(() => {});
      }, 180);
    };
    const observer = new ResizeObserver(update); observer.observe(viewportRef.current); update();
    window.addEventListener('resize', update);
    return () => {alive = false; clearTimeout(timer); observer.disconnect(); window.removeEventListener('resize', update);};
  }, [sessionId, visible, stopped, !!image]);

  function manual(method, args) {
    const work = () => call(method, args);
    const next = inputQueue.current.then(work, work); inputQueue.current = next.catch(() => {}); return next;
  }
  function point(event) {
    const r = imgRef.current.getBoundingClientRect();
    const {width, height} = image || stateRef.current;
    const scale = Math.min(r.width / width, r.height / height);
    const left = r.left + (r.width - width * scale) / 2;
    const top = r.top + (r.height - height * scale) / 2;
    return {x: Math.max(0, Math.min(width - 1, (event.clientX - left) / scale)), y: Math.max(0, Math.min(height - 1, (event.clientY - top) / scale))};
  }
  const mods = e => (e.altKey ? 1 : 0) + (e.ctrlKey ? 2 : 0) + (e.metaKey ? 4 : 0) + (e.shiftKey ? 8 : 0);
  function pointer(event, type) {
    if (!image) return;
    event.preventDefault();
    if (type === 'mousePressed') { down.current = true; event.currentTarget.setPointerCapture(event.pointerId); inputRef.current.focus({preventScroll: true}); }
    if (type === 'mouseMoved') { if (Date.now() - moveTime.current < 45) return; moveTime.current = Date.now(); }
    if (type === 'mouseReleased') down.current = false;
    const args = {...point(event), type, buttons: event.buttons, button: type === 'mouseMoved' ? (event.buttons & 1 ? 'left' : event.buttons & 2 ? 'right' : 'none') : ['left', 'middle', 'right'][event.button] || 'none', modifiers: mods(event), clickCount: Math.max(1, Math.min(2, event.detail || 1))};
    if (type === 'mouseMoved' && !down.current) {
      if (hoverPending.current) return;
      hoverPending.current = true;
      void manual('mouse', args).catch(() => {}).finally(() => { hoverPending.current = false; });
    } else void manual('mouse', args).catch(() => {});
  }
  function keyDown(e) {
    if (e.isComposing || e.nativeEvent?.isComposing || composing.current) return;
    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'v') return;
    if (e.key.length === 1 && !e.ctrlKey && !e.metaKey && !e.altKey) return; // textarea beforeinput handles text/IME
    if (['Shift', 'Control', 'Alt', 'Meta'].includes(e.key)) return;
    e.preventDefault(); e.stopPropagation(); void manual('key', {key: e.key, modifiers: mods(e)}).catch(() => {});
  }
  function commitText(e) {
    if (composing.current || e.nativeEvent?.isComposing) return;
    const text = e.target.value; e.target.value = '';
    if (text) void manual('type', {text}).catch(() => {});
  }
  async function navigate(e) {
    e.preventDefault(); setBusy(true); setError('');
    try { const result = await manual('open', {url: address, engine}); merge(result); merge(await call('state')); }
    finally { setBusy(false); }
  }
  function button(label, onClick, extra = {}) { return h('button', {type: 'button', title: label, 'aria-label': label, onClick: () => { Promise.resolve(onClick()).catch(() => {}); }, ...extra}, extra.children || label); }
  const icon = path => h('svg', {viewBox: '0 0 24 24', width: 19, height: 19, fill: 'none', stroke: 'currentColor', strokeWidth: 1.6, strokeLinecap: 'round', strokeLinejoin: 'round', 'aria-hidden': true}, h('path', {d: path}));

  return h('section', {className: 'dsh-iab-root', 'aria-label': '浏览器'},
    h('div', {className: 'dsh-iab-tabs'},
      state.tabs.map(tab => button(tab.title || '新标签', async () => merge(await manual('select', {targetId: tab.id})), {key: tab.id, className: tab.id === state.active ? 'selected' : '', children: h('span', null, tab.title || '新标签')})),
      button('新建标签', async () => { await manual('open', {url: 'https://www.bing.com/', newTab: true}); merge(await call('state')); }, {children: '+'}),
      state.tabs.length > 0 && button('关闭当前标签', async () => merge(await manual('closeTab', {})), {children: '×'})),
    h('form', {className: 'dsh-iab-toolbar', onSubmit: e => { navigate(e).catch(() => {}); }},
      button('后退', () => manual('back'), {children: icon('M14 5l-7 7 7 7M7 12h13')}), button('前进', () => manual('forward'), {children: icon('M10 5l7 7-7 7M17 12H4')}), button('刷新', () => manual('reload'), {children: icon('M20 11a8 8 0 1 0-2.34 6.66M20 4v7h-7')}),
      h('input', {className: 'dsh-iab-address', 'aria-label': '网址或搜索词', placeholder: '搜索或输入网址', value: address, onChange: e => setAddress(e.target.value), onFocus: e => { addressFocus.current = true; e.target.select(); }, onBlur: () => { addressFocus.current = false; }}),
      busy && h('span', {className: 'dsh-iab-loading', role: 'status', 'aria-label': '正在加载'}, '…'),
      button('暂停AI', async () => {
        setPauseBusy(true);
        try {
          const next = await call('pause', {paused: true}); merge(next);
          if (next.paused) setStatus(next.taskStopped ? '当前 AI 任务已终止' : '浏览器动作已停止');
          else { setStatus(desktop ? '原生浏览器' : '已连接'); setError(''); }
          if (next.paused && !next.taskStopped) setError('浏览器动作已停止，但无法确认模型任务已终止。请同时点击聊天中的停止按钮。');
        } finally { setPauseBusy(false); }
      }, {disabled: pauseBusy || stopped || !state.aiRunning, className: 'dsh-iab-pause' + (state.aiRunning ? ' running' : ''), children: '暂停AI'}),
      button('更多', () => setMore(value => !value), {'aria-expanded': more, children: '⋮'})),
    more && h('div', {className: 'dsh-iab-actions'},
      h('label', null, '搜索 ', h('select', {'aria-label': '搜索引擎', value: engine, onChange: e => setEngine(e.target.value)}, h('option', {value: 'bing'}, '必应'), h('option', {value: 'baidu'}, '百度'), h('option', {value: 'google'}, 'Google')))),
    error && h('div', {className: 'dsh-iab-error', role: 'alert'}, h('span', null, error), button('重新连接', () => { setStopped(false); setNonce(n => n + 1); })),
    state.dialog && h('div', {className: 'dsh-iab-dialog'}, h('span', null, state.dialog.message), button('确定', () => call('dialog', {accept: true})), button('取消', () => call('dialog', {accept: false}))),
    h('div', {className: 'dsh-iab-viewport', ref: viewportRef}, desktop && !stopped && state.mode === 'native' ? null : image && !stopped ? h('img', {
      ref: imgRef, src: image.src, alt: '实时浏览器画面，可直接点击操作', draggable: false,
      onContextMenu: e => e.preventDefault(), onPointerDown: e => pointer(e, 'mousePressed'), onPointerUp: e => pointer(e, 'mouseReleased'), onPointerMove: e => pointer(e, 'mouseMoved'),
      onPointerCancel: e => { down.current = false; void manual('mouse', {...point(e), type: 'mouseReleased', button: 'left', buttons: 0}).catch(() => {}); },
      onWheel: e => { e.stopPropagation(); void manual('scroll', {...point(e), deltaX: Math.max(-5000, Math.min(5000, e.deltaX)), deltaY: Math.max(-5000, Math.min(5000, e.deltaY))}).catch(() => {}); },
    }) : h('div', {className: 'dsh-iab-empty'}, stopped && h('strong', null, '浏览器已关闭'), stopped && h('p', null, '登录资料已保留，下次打开时继续使用。'), stopped && button('打开浏览器', () => { setStopped(false); setNonce(n => n + 1); })),
      h('textarea', {ref: inputRef, className: 'dsh-iab-ime', 'aria-label': '网页键盘输入', autoComplete: 'off', spellCheck: false,
        onKeyDown: keyDown, onChange: commitText, onCompositionStart: () => { composing.current = true; }, onCompositionEnd: e => { composing.current = false; const target = e.target; queueMicrotask(() => commitText({target})); },
        onPaste: e => { e.preventDefault(); const text = e.clipboardData.getData('text/plain'); if (text) void manual('type', {text}).catch(() => {}); },
      })),
    h('footer', {className: 'dsh-iab-footer'}, h('span', {title: desktop ? '真实网页直接渲染，不经过图片压缩' : '当前为画面传输模式；使用原生桌面启动器可获得直接渲染'}, (desktop ? '原生显示' : '兼容显示') + ' · ' + (state.aiRunning ? 'AI 正在运行' : 'AI 未运行')),
      button('关闭浏览器会话', async () => { setStopped(true); setImage(''); await call('closeSession'); })));
}

const css = `
.dsh-iab-root{--iab-bg:var(--background,#fff);--iab-fg:var(--foreground,#273142);--iab-line:rgba(128,128,128,.23);height:100%;min-height:320px;display:flex;flex-direction:column;background:var(--iab-bg);color:var(--iab-fg);font:13px/1.4 system-ui,sans-serif;overflow:hidden}
.dsh-iab-root *{box-sizing:border-box}.dsh-iab-root button,.dsh-iab-root select,.dsh-iab-root input{font:inherit;color:inherit;background:transparent;border:1px solid var(--iab-line);border-radius:6px;min-height:30px;padding:4px 8px}.dsh-iab-root button{cursor:pointer;white-space:nowrap}.dsh-iab-root button:hover{background:rgba(128,128,128,.12)}.dsh-iab-root button:active{background:rgba(128,128,128,.22)}.dsh-iab-root button:disabled{opacity:.5;cursor:wait}.dsh-iab-root :focus-visible{outline:2px solid #4b76df;outline-offset:1px}
.dsh-iab-tabs{display:flex;gap:4px;padding:6px 8px;overflow-x:auto;border-bottom:1px solid var(--iab-line);flex-shrink:0}.dsh-iab-tabs button{max-width:170px;overflow:hidden;text-overflow:ellipsis;border-color:transparent}.dsh-iab-tabs button span{display:block;overflow:hidden;text-overflow:ellipsis}.dsh-iab-tabs .selected{background:rgba(91,125,207,.12);border-color:var(--iab-line)}
.dsh-iab-toolbar{display:flex;gap:4px;padding:8px;flex-shrink:0}.dsh-iab-address{flex:1;min-width:60px}.dsh-iab-actions{display:flex;gap:6px;align-items:center;padding:0 8px 8px;flex-wrap:wrap;flex-shrink:0}.dsh-iab-actions a{color:#527edf}.dsh-iab-root .primary{background:#426dd0;color:#fff;border-color:#426dd0}.dsh-iab-root .primary:hover{background:#365fbd}
.dsh-iab-viewport{position:relative;flex:1 1 0;min-width:0;min-height:150px;contain:size;overflow:hidden;display:flex;align-items:center;justify-content:center;background:#e9ebef}.dsh-iab-viewport img{position:absolute;inset:0;display:block;max-width:none;max-height:none;width:100%;height:100%;object-fit:contain;user-select:none;touch-action:none}.dsh-iab-ime{position:absolute;left:50%;bottom:24px;width:1px;height:1px;opacity:.01;resize:none;padding:0;border:0}.dsh-iab-empty{text-align:center;color:#566075;padding:24px}.dsh-iab-empty strong{display:block;font-size:36px;font-weight:600;line-height:1.25;letter-spacing:2px}.dsh-iab-empty p{max-width:270px}
.dsh-iab-error,.dsh-iab-dialog{display:flex;align-items:center;gap:8px;padding:8px 12px;background:#fff4e5;color:#7b450c;flex-shrink:0}.dsh-iab-error span,.dsh-iab-dialog span{flex:1;overflow-wrap:anywhere}.dsh-iab-footer{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:6px 8px;font-size:11px;border-top:1px solid var(--iab-line);flex-shrink:0}.dsh-iab-footer button{font-size:11px;min-height:24px}
@media(prefers-color-scheme:dark){.dsh-iab-root{--iab-bg:var(--background,#20242c);--iab-fg:var(--foreground,#d5d9e2)}.dsh-iab-viewport{background:#15191f}.dsh-iab-empty{color:#b7bdc9}.dsh-iab-error,.dsh-iab-dialog{background:#3e3021;color:#efc58e}}
.dsh-iab-root{--iab-muted:#858b94;--iab-hover:rgba(128,128,128,.09)}
.dsh-iab-tabs{gap:3px;padding:5px 10px;background:var(--iab-bg);border-bottom:0}
.dsh-iab-tabs button{font-size:12px;min-height:29px;border:0;border-radius:8px;color:var(--iab-muted);padding:4px 10px;max-width:210px}
.dsh-iab-tabs .selected{background:var(--iab-hover);color:var(--iab-fg);border:0}
.dsh-iab-toolbar{gap:3px;align-items:center;padding:7px 10px;margin:0;border-bottom:1px solid var(--iab-line);min-height:48px}
.dsh-iab-toolbar button{display:inline-flex;align-items:center;justify-content:center;flex:0 0 32px;width:32px;height:32px;min-height:32px;padding:0;border:0;border-radius:8px;color:var(--iab-muted);font-size:23px;line-height:1}
.dsh-iab-toolbar button:hover{background:var(--iab-hover);color:var(--iab-fg)}
.dsh-iab-toolbar .dsh-iab-address{flex:1;min-width:0;height:32px;padding:4px 12px;border:1px solid rgba(128,128,128,.48);border-radius:8px;text-align:left;background:var(--iab-hover);color:var(--iab-fg);font-size:13px;text-overflow:ellipsis}
.dsh-iab-toolbar .dsh-iab-address::placeholder{color:var(--iab-muted)}
.dsh-iab-toolbar .dsh-iab-address:hover{border-color:rgba(128,128,128,.7)}
.dsh-iab-toolbar .dsh-iab-address:focus{border-color:#7699df;text-align:left;background:var(--iab-hover);outline:2px solid #7699df;outline-offset:0}
.dsh-iab-actions{padding:8px 12px;border-bottom:1px solid var(--iab-line);gap:14px;font-size:12px;color:var(--iab-muted)}
.dsh-iab-actions select{font-size:12px;border:0;background:var(--iab-hover);min-height:28px}
.dsh-iab-footer{min-height:28px;padding:3px 10px;color:var(--iab-muted);font-size:10px}
.dsh-iab-footer button{border:0;color:var(--iab-muted);font-size:10px}
.dsh-iab-toolbar .dsh-iab-pause{flex:0 0 auto;width:auto;padding:0 10px;font-size:12px;font-weight:600;color:var(--iab-muted);background:var(--iab-hover)}
.dsh-iab-toolbar .dsh-iab-pause:disabled{opacity:1;cursor:default}
.dsh-iab-toolbar .dsh-iab-pause.running{color:#fff;background:#c53030}
.dsh-iab-toolbar .dsh-iab-pause.running:hover{background:#a82020}
.dsh-iab-loading{color:var(--iab-muted);font-size:15px}
@media(max-width:600px){.dsh-iab-toolbar{padding:6px;gap:1px}.dsh-iab-toolbar button{width:28px;flex-basis:28px}.dsh-iab-tabs button{max-width:150px}.dsh-iab-actions{gap:8px}}
`;

exports.inject = ['betterSidebar'];
exports.apply = function apply(ctx) {
  const api = createApi();
  ctx.effect(() => {
    const style = document.createElement('style'); style.dataset.plugin = 'dsh-inapp-browser'; style.textContent = css; document.head.appendChild(style);
    return () => style.remove();
  });
  ctx.effect(() => ctx.betterSidebar.registerTab({
    id: TAB, title: '浏览器', description: '真实网页 · 鼠标操作 · AI 截图检查', single: true, order: 65,
    icon: h('span', {'aria-hidden': true}, '◎'),
    component: props => h(BrowserPanel, {...props, api, key: props.scope.sessionId}),
  }));
  ctx.effect(() => {
    let stopped = false, timer; const seen = new Map(); const abort = new AbortController();
    const poll = async () => {
      try {
        const {items} = await api.call('activity', {}, abort.signal);
        for (const item of items) if (seen.get(item.sessionId) !== item.stamp) {
          seen.set(item.sessionId, item.stamp);
          ctx.betterSidebar.openTab({type: TAB, target: 'right'}, {sessionId: item.sessionId});
        }
      } catch {} // A restart may briefly remove host routes; the mounted panel shows actionable failures.
      if (!stopped) timer = setTimeout(poll, 2000);
    };
    void poll(); return () => { stopped = true; clearTimeout(timer); abort.abort(); };
  });
};

return module.exports;
}});
