import { readFile, mkdir, writeFile } from 'node:fs/promises';
const source = await readFile(new URL('../src/client.cjs', import.meta.url), 'utf8');
await mkdir(new URL('../lib/', import.meta.url), {recursive: true});
await writeFile(new URL('../lib/client.js', import.meta.url),
  '// Generated by npm run build. Edit src/client.cjs.\nwindow.__ModuleLoader__.load({id:"dsh-inapp-browser",factory:(require)=>{\nconst module={exports:{}};const exports=module.exports;\n' + source + '\nreturn module.exports;\n}});\n');
console.log('Built lib/client.js (Harness module factory; React stays external).');
